/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

export function Planet({ colors, ...props }) {
  const shapeContainer = useRef(null);
  const shperesContainer = useRef(null);
  const ringContainer = useRef(null);
  const { nodes, materials } = useGLTF("/models/Planet.glb");

  // Clone materials so we can safely override per-part colors/properties
  const mainSphereMat = useMemo(() => materials["Material.002"].clone(), [materials]);
  const smallSphereMat = useMemo(() => materials["Material.001"].clone(), [materials]);
  const ringMat = useMemo(() => materials["Material.001"].clone(), [materials]);

  // Apply color overrides if provided
  useEffect(() => {
    // Ring: use original material unless override provided
    if (colors?.ring) ringMat.color.set(colors.ring);

    // Small sphere: use original material unless override provided
    if (colors?.smallSphere) {
      smallSphereMat.color.set(colors.smallSphere);
      if ("metalness" in smallSphereMat && colors?.smallSphereMetalness !== undefined) {
        smallSphereMat.metalness = colors.smallSphereMetalness;
      }
      if ("roughness" in smallSphereMat && colors?.smallSphereRoughness !== undefined) {
        smallSphereMat.roughness = colors.smallSphereRoughness;
      }
    }

    // Main sphere: use original unless override provided
    if (colors?.sphere) mainSphereMat.color.set(colors.sphere);
  }, [colors, ringMat, smallSphereMat, mainSphereMat]);

  useGSAP(() => {
    const tl = gsap.timeline();
    tl.from(shapeContainer.current.position, {
      y: 5,
      duration: 3,
      ease: "circ.out",
    });
    tl.from(
      shperesContainer.current.rotation,
      {
        x: 0,
        y: Math.PI,
        z: -Math.PI,
        duration: 10,
        ease: "power1.inOut",
      },
      "-=25%"
    );
    tl.from(
      ringContainer.current.rotation,
      {
        x: 0.8,
        y: 0,
        z: 0,
        duration: 10,
        ease: "power1.inOut",
      },
      "<"
    );
  }, []);

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={shperesContainer}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={mainSphereMat}
          rotation={[0, 0, 0.741]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere2.geometry}
          material={smallSphereMat}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>
      <mesh
        ref={ringContainer}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={ringMat}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload("/models/Planet.glb");
